# Generated by Django 4.2.3 on 2023-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_active_productline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='p', max_length=100),
            preserve_default=False,
        ),
    ]
