# Generated by Django 4.2.3 on 2024-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_attribute_attributevalue_productlineattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_line_attribute_value', through='product.ProductLineAttributeValue', to='product.attributevalue'),
        ),
    ]
