# Generated by Django 4.2.3 on 2024-03-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productline_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.producttype'),
            preserve_default=False,
        ),
    ]
