# Generated by Django 4.2.3 on 2024-03-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
