# Generated by Django 4.2.3 on 2024-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_created_at_product_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='weight',
            field=models.FloatField(),
        ),
    ]
