# Generated by Django 4.2.3 on 2024-03-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_pid_alter_productline_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='productline',
            new_name='product_line',
        ),
    ]
