# Generated by Django 4.2.3 on 2024-03-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_productline_productimage_product_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_line_type', to='product.producttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_type', to='product.producttype'),
        ),
    ]
