# Generated by Django 4.2.3 on 2024-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_attribute_value', through='product.ProductAttributeValue', to='product.attributevalue'),
        ),
    ]
